-- EXERCÍCIOS: FAÇA VOCÊ MESMO --

-- 1- SELECIONE OS PRIMEIROS 5 REGISTROS DA TABELA CLIENTES, ORDENANDO-OS PELO NOME EM ORDEM CRESCENTE. --
SELECT * FROM clientestabela 
ORDER BY nome_cliente ASC 
LIMIT 5;

-- 2- ENCONTRE TODOS OS PRODUTOS NA TABELA PRODUTOS QUE NÃO TÊM UMA DESCRIÇÃO ASSOCIADA (SUPONHA QUE A COLUNA DE DESCRIÇÃO POSSA SER NULA). --
SELECT * FROM tabelaprodutos
WHERE descrição ISNULL;

-- 3- LISTE OS FUNCIONÁRIOS CUJO NOME COMEÇA COM 'A' E TERMINA COM 'S' NA TABELA FUNCIONARIOS. --
SELECT * FROM funcionariostabela
WHERE nome_funcionario LIKE 'A%' AND nome LIKE '%s';

-- 4- EXIBA O DEPARTAMENTO E A MÉDIA SALARIAL DOS FUNCIONÁRIOS EM CADA DEPARTAMENTO NA TABELA FUNCIONARIOS, AGRUPANDO POR DEPARTAMENTO, APENAS PARA OS DEPARTAMENTOS CUJA MÉDIA SALARIAL É SUPERIOR A $5000. --
SELECT departamento, ROUND(AVG(salario),2) as Media_Salarial
FROM funcionariostabela
GROUP BY departamento
HAVING Media_Salarial > 5000;

-- 5- SELECIONE TODOS OS CLIENTES DA TABELA CLIENTES E CONCATENE O PRIMEIRO E O ÚLTIMO NOME, ALÉM DE CALCULAR O COMPRIMENTO TOTAL DO NOME COMPLETO. --
SELECT ('O nome do cliente é ' || nome_cliente || ' e o comprimento do seu nome é de ' || LENGTH(nome_cliente) || '.') as TEXT from clientestabela;
        
-- 6- PARA CADA VENDA NA TABELA VENDAS, EXIBA O ID DA VENDA, A DATA DA VENDA E A DIFERENÇA EM DIAS ENTRE A DATA DA VENDA E A DATA ATUAL. --
SELECT id, data_do_pedido, ROUND(JULIANDAY('NOW') - JULIANDAY(data_do_pedido),0) 
as Diferenca_Dias 
FROM tabelapedidos;

-- 7- SELECIONE TODOS OS ITENS DA TABELA PEDIDOS E ARREDONDE O PREÇO TOTAL PARA O NÚMERO INTEIRO MAIS PRÓXIMO. --
SELECT id, ROUND(total_do_pedido) as Total_do_Pedido_Arredondado
from tabelapedidos;

-- 8- CONVERTA A COLUNA DATA_STRING DA TABELA EVENTOS, QUE ESTÁ EM FORMATO DE TEXTO (YYYY-MM-DD), PARA O TIPO DE DATA E SELECIONE TODOS OS EVENTOS APÓS '2023-01-01'. --
SELECT * FROM eventos
WHERE CAST(data_string AS DATE) > '2023-01-01';

-- 9- NA TABELA AVALIACOES, CLASSIFIQUE CADA AVALIAÇÃO COMO 'BOA', 'MÉDIA', OU 'RUIM' COM BASE NA PONTUAÇÃO: 1-3 PARA 'RUIM', 4-7 PARA 'MÉDIA', E 8-10 PARA 'BOA'. --
SELECT nome_aluno, nota,
CASE
        WHEN nota BETWEEN 1 AND 3 THEN 'Ruim'
        WHEN nota BETWEEN 4 AND 7 THEN 'Média'
        ELSE 'Boa'
        END AS avaliacao
FROM avaliacoes;

-- 10- ALTERE O NOME DA COLUNA DATA_NASC PARA DATA_NASCIMENTO NA TABELA FUNCIONARIOS E SELECIONE TODOS OS FUNCIONÁRIOS QUE NASCERAM APÓS '1990-01-01'. --
ALTER TABLE funcionarios RENAME COLUMN data_nasc TO data_nascimento; 

SELECT * FROM funcionarios WHERE CAST (data_nascimento AS DATE) > '1990-01-01';
